baseurl = "http://lsca94.github.io"
title = "lorisscandurra"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Loris Scandurra"
  info = "Cloud Architect"
  description = "Loris Scandurra's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/lsca94/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 2
  url = "https://instagram.com/lorisscandurra/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "http://www.linkedin.com/in/giuseppelorisscandurra"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope-o fa-2x"
  weight = 4
  url = "mailto:ls@lorisscandurra.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
#[[menu.main]]
#  name = "About"
#  weight = 2
#  url = "about/"
